# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: keyescloudsolutions
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: pythontest
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Python-Test

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
